### ISSUE TITLE
There is occasional high RAM and CPU use when there is a large number of tabs.

### ISSUE THREAD

**Issue by Poikilos** [canalun/tree-tab-sidebar#2]
# What happened?
There is high CPU and RAM use when there are many tabs.

![image](https://github.com/canalun/tree-tab-sidebar/assets/7557867/c7382ee8-3660-43ec-b9e1-4fc08492203b)

# When?
- When there are many tabs (200?)
- Brave Version 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
- When I first installed the extension and restarted my browser, the browser became sluggish, and the CPU fan started coming on. After that, the slowness and CPU fan continued to come on every once in a while.
- After a while, it subsides, down to 202 MB memory, 0.0 CPU (minutes after the screenshot above).
- I can't establish a pattern of when it occurs. Maybe when I made a new tab? Maybe when there are multiple YouTube tabs? Making new tabs *sometimes* is slow and takes several seconds to respond to switching to a new tab.
- I use Marvelous Suspender (since The Great Suspender's privacy is said to be compromised). During the slow times, the sidebar has blank (circle) icons for the suspended tabs, but eventually loads ghosted ones. This process is slow with Brave's built-in vertical tabs mode as well, but not as slow and does not trigger the CPU fan nor the slowness to respond to clicks when Tree Tab Sidebar is not installed.

If there were a way to make Brave not try to load its own tabs I would like to test that and I can get back to you on the results. However, my searches indicate there is no way to do that (The "Immersive Fullscreen Toolbar" is no longer in "chrome://flags", and I can't be sure that would disable the most intensive related background jobs).

If there were some way to back up the tabs and put them in Chrome, I could test this further using Chrome rather than Brave.

**Comment by Poikilos** [comment]
Hmm... It turns out that I had over 1300 tabs open, probably tabs from over 3 years. I have saved them to a folder and I'll try to mend my ways.

**Comment by canalun** [comment]
got it, thank you for reporting the issue!
